# Generated by Django 3.2 on 2021-04-15 10:26

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("part", models.CharField(max_length=100)),
                ("part_category", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="part",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "category", "model", "part", "part_category"),
                name="unique_part_entry",
            ),
        ),
    ]
