name: Check & Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ci_db_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: pip install flake8 black isort -r requirements.txt

      - name: Lint
        run: black --check . && isort --check . && flake8 .

      - name: Check migrations
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: ci_db_test
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: fefwefgrsgagwegf2352
        run: python manage.py migrate

      - name: Run tests
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: ci_db_test
          DB_HOST: localhost
          DB_PORT: 5432
          SECRET_KEY: fefwefgrsgagwegf2352
        run: python manage.py test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Todo: tag image with branch names.
      - name: Build and push
        if: github.ref == 'refs/heads/main'
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: shiprashalini/urparts:latest

